name: Build and Publish
on: [push]
jobs:
  build_vue:
    name: build
    runs-on: ubuntu-latest 
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: git cmd setup
      run: |
        git config --global user.email "${{ github.actor }}"
        git config --global user.name "${{ github.actor }}@users.noreply.github.com"
    - run: npm i
    - run: npm run build
    - name: ghPages (w/404hack)
      run: |
        cd dist
        ln -s index.html 404.html
        git init
        git add -A
        git commit -m "autoPublish: ${{ github.sha }}"
        git push -f https://${{ github.repository_owner }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{github.repository}}.git master:gh-pages